version: '3.8'

services:
  api:
    image: fawazsullialabs/roam-eazy-api:0.0.2
    ports:
      - "9005:9005"
    env_file:
      - .prod.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: fawazsullialabs/roam-eazy-ui:0.0.1
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"